export const DummySoulcorePlayers: Record<string, string[]> = {
  a: [
    'Astronis',
    'Addons',
    'Aaron Soulbringer',
    'Apu Nahasapeemapetilon',
    'Apocalyptic Warlord',
    'Alpha Player',
    'Adventurer',
    'Arcane Druid',
    'Arctic Knight',
    'Ancient Paladin',
  ],
  b: [
    'Bubble',
    'Breaker',
    'Big Black Clockerino',
    'Bloodbringer',
    'Bubble',
    'Blazing Warrior',
    'Black Knight User',
    'Bleeding Edge',
    'Blue Mage',
    'Bounty Hunter',
  ],
  c: [
    'Captain‑Barbossa',
    'Casanna',
    'Cerepton',
    'Cold Storme',
    'Chimbinha Quebate',
    'Clausete',
    'Classic Knight',
    'Cool Sorcerer',
    'Crimson Druid',
    'Cerulean Paladin',
  ],
  d: [
    'Deathwalker',
    'Duzе Jajca',
    'Dimitri von Carstein',
    'Dark Mortals',
    "Diego Del'Toro",
    'Drift Toknight',
    'David Coppershield',
    'Dragonas',
    'Dking',
    'Dread Pirate',
  ],
  e: [
    'Eternal Oblivion',
    'Ender',
    'Elite Knight Hero',
    'Ectonius II',
    'Emil',
    'Ek',
    'Eternal Mage',
    'Exalted Healer',
    'Ethereal Paladin',
    'Everlast Sorcerer',
  ],
  f: [
    'Fadrin Lucas',
    'Fern',
    'Fena Imrae',
    'Foppa on Rook',
    'Feet for Hands',
    'Flameberg',
    'Footkicker',
    'Fearless Druid',
    'Forsaken Knight',
    'Frozen Wizard',
  ],
  g: [
    'God Of Glory',
    'Garimo',
    'Glow Paladin',
    'Garganfunker',
    'Giant Panda',
    'Grim Warlord',
    'Ghost Hunter',
    'Galathor',
    'Gothic Knight',
    'Golden Mage',
  ],
  h: [
    'Harry Botter',
    'Hugh janis',
    'Himberna Legend',
    'Himberna Gang Rep',
    'Himmelhüpferin',
    'Holy Ghost',
    'Holy Union Member',
    'Hex Master',
    'Hunched Knight',
    'Heroic Paladin',
  ],
  i: [
    'Invinvible Aznx',
    'Infected',
    'Invader Sorcerer',
    'Ice Mage',
    'Iron Lord',
    'Illusive Knight',
    'Imperial Druid',
    'Infinite Warrior',
    'Icy Healer',
    'Invincible Paladin',
  ],
  j: [
    'JuGgernaut',
    'Jkiller',
    'Julera',
    'Jofiwug',
    'Jester Sorcerer',
    'Justice Knight',
    'Jaded Druid',
    'Jester Mage',
    'Jagged Paladin',
    'Jaded Warlock',
  ],
  k: [
    'Kolskägg',
    'Kushrynada',
    'Killer Knight',
    'Knightmare',
    'Kotku',
    'Katana Quester',
    'Kold Frost',
    'Kraken Slayer',
    'Karmeya Hero',
    'Kingmaker',
  ],
  l: [
    'Lute Montesco',
    'Liebre',
    'Lizziet',
    'Lauton Paladin',
    'Legacy Sorcerer',
    'Lightbringer',
    'Luciforms The Great',
    'Loyal Druid',
    'Legendary Healer',
    'Lycan Knight',
  ],
  m: [
    'Mix Master Prodip',
    'Mateusz Dragon Wielki',
    'Master Morla',
    'Messiah',
    'Merlkin',
    'Mystic Avatar',
    'Monk',
    "Mediota Del'Toro",
    'Mozani',
    'Mazara Paladin',
  ],
  n: [
    'Nunka q vai dar',
    'Nils',
    'Nöber',
    'No Pain _/',
    'Nightblade',
    'Neo Sir',
    'Naga Sorcerer',
    'Nightstalker',
    'Nomad Paladin',
    'Noble Healer',
  ],
  o: [
    'Ouroborous',
    'Old Rubera Legend',
    'Oculon Mage',
    'Obscured Knight',
    'Ornate Druid',
    'Orion Healer',
    'Oathbreaker',
    'Omega Paladin',
    'Opal Warrior',
    'Orion Sorcerer',
  ],
  p: [
    'Painful Hands',
    'Pablo Pikinha',
    'Pan Sernik',
    'Paskanaamainen',
    'Platynka',
    'Prince of cachorro',
    'Phantom Knight',
    'Pure Druid',
    'Pursuer Sorcerer',
    'Protector Paladin',
  ],
  q: [
    'Quiefer Sutherland',
    'Quester Mage',
    'Queen Paladin',
    'Quantum Druid',
    'Quiet Healer',
    'Quetzal Knight',
    'Questmaster',
    'Quasar Warlock',
    'Quixotic Sorcerer',
    'Quiver Archon',
  ],
  r: [
    'Reaper Of The Forgoten',
    'Rattractive',
    'Ratsy',
    'Raze Knight',
    'Ruthless Seven Member',
    'Refugia Hero',
    'Rasunik Nevah',
    'Royal Paladin Guest',
    'Ravage Druid',
    'Rift Sorcerer',
  ],
  s: [
    'Sir Duckie',
    'Silent Defender',
    'Sigismund',
    'Sassy Blondie',
    'Skogis',
    'Skopz Paladin',
    'Savage Funkstar',
    'SNETRIPP',
    'Surenix Sorcerer',
    'Soulbringer',
  ],
  t: [
    'Takhisiss',
    'Tomek',
    'Tetzti',
    'Thief of The Myth',
    'Thug Family',
    'Tiddy Bear',
    'True Warlord of Silvera',
    'Tzetzi',
    'Titan Knight',
    'Twilight Druid',
  ],
  u: [
    'Undying Mage',
    'Ultimate Paladin',
    'Unchained Druid',
    'Undefeated Sorcerer',
    'Unaffected Healer',
    'Ultrafrost Knight',
    'Unseen Warlock',
    'Utopia Warrior',
    'Umbra Druid',
    'Union Member',
  ],
  v: [
    'Vyses Darkheart',
    'Vunira Veteran',
    'Victorious Paladin',
    'Vandal Sorcerer',
    'Voca Mage',
    'Valorous Healer',
    'Vanguard Knight',
    'Viper Druid',
    'Vindicator',
    'Voidwalker',
  ],
  w: [
    'WarHell',
    'Wattsy',
    'Warm Cat',
    'Warrior King',
    'Wild Sorcerer',
    'Wizard Lord',
    'Witcher Quester',
    'White Paladin',
    'Warlord of Glory',
    'World Healer',
  ],
  x: [
    'Ximet',
    'Xezozez',
    'Xiq',
    'Xerena Hero',
    'Xybra Knight',
    'Xyra Sorcerer',
    'Xorian Paladin',
    'Xeno Druid',
    'Xcalibur Warrior',
    'Xtravaganza',
  ],
  y: [
    'Yielothax',
    'Yutari Mage',
    'Yara Paladin',
    'Yovera Hero',
    'Yuna Sorcerer',
    'Yaldar Healer',
    'Young Warrior',
    'Ytarian Knight',
    'Yven Druid',
    'Yielding Warlord',
  ],
  z: [
    'Zorbat',
    'Zyrie',
    'Zu',
    'Zendrix',
    'Zapp Brannigen',
    'Zephyra Healer',
    'Zauber Sorcerer',
    'Zelda Slayer',
    'Zion Knight',
    'Zul Warrior',
  ],
};
