export const DummySoulcoreCreatures: Record<string, string[]> = {
  a: [
    'Abominable Servant',
    'Abominable Spawn',
    'Abyssador',
    'Abyssal Calamary',
    'Achad',
    'Acid Blob',
    'Acolyte of Darkness',
    'Acolyte of the Cult',
    'Adept of the Cult',
    'Adult Goanna',
    'Adventurer',
    'Afflicted Strider',
    'Aggressive Chicken',
    'Agrestic Chicken',
    'Ahau',
    'Albino Dragon',
    'Alchemistical Container',
    'Alptramun',
    'Amazon',
    'Amenef the Burning',
    'Ancient Lion Archer',
    'Ancient Lion Knight',
    'Ancient Scarab',
    'Ancient Spawn of Morgathla',
    'Ancient Ugly Monster',
    'Angry Adventurer',
    'Angry Demon',
    'Angry Elemental',
    'Angry Plant',
    'Angry Sugar Fairy',
    'Animated Clomp',
    'Animated Cyclops',
    'Animated Feather',
    'Animated Guzzlemaw',
    'Animated Moohtant',
    'Animated Mummy',
    'Animated Ogre Brute',
    'Animated Ogre Savage',
    'Animated Rotworm',
    'Animated Snowman',
    'Annihilon',
    'Annoying Dog',
    'Antenna',
    'Apprentice Sheng',
    'Arachir the Ancient One',
    'Arachnophobica',
    'Arctic Faun',
    'Armadile',
    'Armenius',
    'Arthom the Hunter',
    'Ashmunrah',
    'Askarak Demon',
    'Assassin',
    'Atab',
    'Avalanche',
    'Axeitus Headbanger',
  ],
  b: [
    'Baboon',
    'Banshee',
    'Barbarian',
    'Basilisk',
    'Bat',
    'Behemoth',
    "Bertoxxulous' Handmaiden",
    'Black Knight',
    'Blood Crab',
    'Blood Priestess',
    'Boar',
    'Bonebeast',
    'Bugbear',
    'Buromops',
    'Burning Gladiator',
    'Burster',
    'Burster',
    'Bunyip',
  ],
  c: [
    'Cadaver',
    'Calamary',
    'Captain Zao',
    'Carlin Troll',
    'Carniphila',
    'Cave Rat',
    'Cave Devourer',
    'Centipede',
    'Chaos Elemental',
    'Chameleos',
    'Choking Fear',
    'Cockroach',
    'Corrupted Djinn',
    'Crab',
    'Crustaceous Crustacean',
    'Crystal Spider',
    'Cyclops',
  ],
  d: [
    'Dark Torturer',
    'Dark Wolf',
    'Death Blob',
    'Deathbringer',
    'Deepsea Blood Crab',
    'Deepling Guard',
    'Demon',
    'Demon Skeleton',
    'Desert Hunter',
    'Devourer',
    'Diablo',
    'Doll',
    'Dragon',
    'Dwarf Guard',
    'Dwarf Soldier',
    'Dwarf',
  ],
  e: [
    'Elder Wyrm',
    'Electrocutioner',
    'Energy Elemental',
    'Essence of a Dream',
    'Et',
    'Evil Sheep',
    'Experiment',
    'Ethereal Wraith',
  ],
  f: [
    'Falcon',
    'Fanged Devourer',
    'Fenrir',
    'Feroxa',
    'Fire Devil',
    'Flamingo',
    'Frost Dragon',
    'Frost Giant',
    'Furious Sleeper',
  ],
  g: [
    'Gargoyle',
    'Ghoul',
    'Ghost',
    'Giant Spider',
    'Glooth Bandit',
    'Glooth Blob',
    'Golem',
    'Gore Horn',
    'Grim Reaper',
  ],
  h: [
    'Haunted Treeling',
    'Hellhound',
    'Hemp Rope',
    'Horned Fox',
    'Horrible Thing',
    'Hydra',
  ],
  i: [
    'Ice Golem',
    'Ice Witch',
    'Iks Ahpututu',
    'Imp',
    'Infernatil',
    'Insectoid',
    'Irongolem',
  ],
  j: ['Jal', 'Juggernaut', 'Jester', 'Jewel Dragon', 'Jal'],
  k: ['Killing Machine', 'Knight', 'Kongra', 'Killer Caiman', 'Kraken'],
  l: [
    'Lich',
    'Lizard',
    'Lizard Chosen',
    'Lost Soul',
    'Lycan',
    'Larva',
    'Lightning Elemental',
  ],
  m: [
    'Magma Coat',
    'Mammoth',
    'Marsh Stalker',
    'Medusa',
    'Merlkin',
    'Minotaur',
    'Monkey',
    'Moohtant',
    'Mummy',
    'Mutated Human',
  ],
  n: [
    'Necropharus',
    'Nightmare',
    'Nightmare Knight',
    'Nightmare Scion',
    'Nightmare Spectre',
    'Naga',
    'Naga Warrior',
  ],
  o: [
    'Orc',
    'Orc Berserker',
    'Orc Leader',
    'Orc Shaman',
    'Ogre',
    'Ogre Brute',
    'Ogre Savage',
    'Ogre Shaman',
    'Oodok Witchmaster',
    'Orc Musician',
  ],
  p: [
    'Parasite',
    'Pharaoh',
    'Phantasm',
    'Pirate',
    'Pirate Buccaneer',
    'Pirate Ghost',
    'Pirate Skeleton',
    'Plaguesmith',
    'Poison Spider',
  ],
  q: [
    'Quara Constrictor',
    'Quara Hydromancer',
    'Quara Mantassin',
    'Quara Pincher',
    'Quara Predator',
    'Quara Venom',
    'Quara X',
  ],
  r: [
    'Raging Fire',
    'Rathleton Explorer',
    'Ravenous Lava Lurker',
    'Red Dragon',
    'Rotworm',
    'Rotten Ghoul',
    'Royal Paladin',
    'Rupture the Horned Fox',
  ],
  s: [
    'Salamander',
    'Sandcrawler',
    'Scarab',
    'Scar Tribe Shaman',
    'Servant of Tentugly',
    'Shadow Stalker',
    'Shaburak Demon',
    'Sheep',
    'Skeleton',
    'Slime',
    'Snow Troll',
    'Soul of a Fey',
    'Spider',
    'Spirit',
    'Steam Elemental',
  ],
  t: [
    'Tarantula',
    'Taurus',
    'Tibia Boss',
    'Tiger',
    'Titan Drone',
    'Toxic Titan',
    'Troll',
    'Turtlemaster',
    'Twisted Pooka',
  ],
  u: [
    'Undead Dragon',
    'Undead Dragon',
    'Undead Scavenger',
    'Unholy Bonekeeper',
  ],
  v: [
    'Vampire',
    'Vampire Bride',
    'Vampire Lord',
    'Venerable Lich',
    'Vile Destroyer',
  ],
  w: [
    'War Golem',
    'Weakened Shroom',
    'Werelion',
    'White Deer',
    'Wild Warrior',
    'Wolf',
    'Wyrm',
  ],
  x: ['Xenia', 'Xenora', 'Xycron'],
  y: ['Yellow Toilet Paper Man', 'Yielothax', 'Yeti', 'Young Sea Serpent'],
  z: ['Zalamon', 'Zorbat', 'Zushuka'],
};
